---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jellyfin-tls
  namespace: traefik
spec:
  dnsNames:
    - 'jellyfin.lzv2734l60.ftc3iai.shoot.emk.fuga.cloud'
  secretName: jellyfin-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: whoami-tls
  namespace: traefik
spec:
  dnsNames:
    - 'whoami.lzv2734l60.ftc3iai.shoot.emk.fuga.cloud'
  secretName: whoami-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer    
